# Generated by Django 3.0.3 on 2020-02-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Currency')),
            ],
            options={
                'unique_together': {('currency', 'valid_from'), ('currency', 'valid_until')},
            },
        ),
    ]
