# Generated by Django 3.0.3 on 2020-02-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeratehistory',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='exchangeratehistory',
            unique_together={('currency', 'valid_from')},
        ),
    ]
